/*
 * This source file was generated by the Gradle 'init' task
 */
package com.lament.z.omni.mhub;

import com.lament.z.omni.mhub.config.omni.OmniMediaHubProperties;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.boot.context.properties.EnableConfigurationProperties;

@SpringBootApplication
@EnableConfigurationProperties({OmniMediaHubProperties.class})
public class OmniMediaHubApplication {

    public static void main(String[] args) {
        SpringApplication.run(OmniMediaHubApplication.class, args);
    }
}
